apiVersion: v2
name: workload-type-1
description: A Helm chart for workload-type-1 scheduled workload
type: application
version: 0.1.0
appVersion: "v1.0.0"
keywords:
  - workload
  - scheduled-workload
  - energy-monitoring
maintainers:
  - name: Hiro Team