apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-aware-orchestrator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: energy-aware-orchestrator
rules:
  - apiGroups: ["eas.hiro.io"]
    resources:
      - energyawareorchestrations
      - energyawareorchestrations/status
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: energy-aware-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: energy-aware-orchestrator
subjects:
  - kind: ServiceAccount
    name: energy-aware-orchestrator
    namespace: default



