apiVersion: eas.hiro.io/v1
kind: EnergyAwareOrchestration
metadata:
  name: app-process
  namespace: default
spec:
  applicationRef:
    name: my-app
    namespace: my-namespace
  energyConsumption: 1000
  forecastWindowDays: 7
  priority: Critical



