apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload-type-1.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workload-type-1.labels" . | nindent 4 }}
data:
  morning_start: {{ .Values.configMap.morningStart | quote }}
  morning_end: {{ .Values.configMap.morningEnd | quote }}
  evening_start: {{ .Values.configMap.eveningStart | quote }}
  evening_end: {{ .Values.configMap.eveningEnd | quote }}
  computation_duration: {{ .Values.configMap.computationDuration | quote }}
  log_level: {{ .Values.configMap.logLevel | quote }}
  max_cpu_cores: {{ .Values.configMap.maxCpuCores | quote }}