apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMap.envName }}
  labels:
    app: {{ .Values.app.name }}
data:
  env.js: |
    window.__env = {
      apiUrl: "{{ .Values.app.env.API_TARGET }}",
      k8sProxyUrl: "{{ .Values.app.env.K8S_PROXY_TARGET | default .Values.app.k8sProxy.ingress.host }}"
    };
